apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: academind/kub-data-demo:2
          # 환경 변수 설정
          env:
            # 환경 변수의 이름 설정
            - name: STORY_FOLDER
              # value를 통해서 환경 변수의 key에 대한 값을 지정
              # value: 'story'
              # 다른 파일의 환경 변수 값을 가져오기 위한 설정
              valueFrom: 
                # 키 참조를 의미. 특정 configMap을 가리킴
                configMapKeyRef:
                  # 참조하려는 configMap의 이름과 키 지정
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc