# 영구 볼륨을 사용하기 위한 claim 작성
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  # 우리가 사용할 영구 볼륨을 지정함
  volumeName: host-pv
  # 사용할 access mode 지정 영구 볼륨 셋팅과 맞춤
  accessModes:
    - ReadWriteOnce
  # 스토리지 클래스 설정
  storageClassName: standard
   # 이 claim에서 얻고자 하는 리소스 지정
  resources:
    requests: 
      # 영구 볼륨 셋티의 capacity와 대응
      # 동일한 영구 볼륨에 대해서 여러 claim이 있는 경우 capacity에서 셋팅한 값보다 낮게 설정 가능
      # pod에서 모든 claim을 사용하려 하고, 용량보다 많은 데이터를 사용하면 오류가 발생하기 때문에
      storage: 1Gi