apiVersion: v1
# 영구 볼륨으로 정의
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  # 관리자로서 나중에 클러스터에 실행되는 pod에서 사용할 수 있는 capacity를 제어하기 위해 설정
  # 따라서 아래에 용량을 설정할 수 있음 (capacity: 용량)
  # 나중에 이 볼륨을 요구할 때, 필요한 용량을 정의 (영구 볼륨 및 pod의 용량을 셋팅)
  capacity: 
     # hostPath의 볼륨을 최대 1GB로 공간을 확보 및 사용하도록 설정
    storage: 1Gi # 기가 바이트 표기가 이 코드와 같음
  # Filesystem, Block 2개지 모드가 있음
  # Filesystem: 가상 머신 내부의 파일 시스템에 폴더가 있음
  volumeMode: Filesystem
  # standard는 디폴트로 설정되어있는 스토리지 클래스로 우리가 만드려는 스토리지의 정보를 가지고 있음
  storageClassName: standard
  # access 방법에 대해 설정으로 주어진 pod를 위한 볼륨을 만드는 방법을 정의
  accessModes:
    # -를 이용해 모든 access 방법을 나열할 수 있음
    # ReadWriteOnce: 단일 노드에 의해, 읽기/쓰기 볼륨으로 마운트 될 수 있음 
    # 따라서, 여러 pod에 의해 수행되지만, 모두 동일한 노드에 있어야함
    - ReadWriteOnce
    # - ReadOnlyMany: 읽기 전용이지만, 여러 노드에서 요청할 수 있음 따라서, 다른 노드의 여러 pod가 동일한 영구 볼륨에 요청 가능
    #   하지만, hostPath의 경우 하나의 노드에 정의되어 다른 노드에 제공하여 다른 노드에서 실행되는
    #   다른 pod는 이를 생성할 수 없기 때문에 사용 불가
    # - ReadWriteMany: 여러 노드에서 요청할 수 있음 따라서, 다른 노드의 여러 pod가 동일한 영구 볼륨에 요청 가능
    #   하지만 ReadOnlyMany와 같이 다른 pod에서 생성이 불가능해 hostPath에서 사용 불가
  # hostPath로 영구 볼륨을 만드는 것이기 때문에 아래와 같이 설정
  hostPath:
    path: /data
    type: DirectoryOrCreate