apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      # 포트를 8000을 가리키므로 서정
      port: 8000
      targetPort: 8000