apiVersion: v1 # service는 core 그룹이기 때문에 v1으로 생략 가능
kind: Service # service를 만들기 때문에 kind를 service로 지정
metadata: # service를 정의
  name: backend # service의 이름을 지정
spec: # service의 spec을 설정
  selector: # 제어할 pod의 label을 지정
    app: second-app # 이 레이블을 가진 모든 pod를 service에 의해서 제어
  ports: # ports를 통해서 하나 이상의 port를 노출할 수 있음
    - protocol: 'TCP' # protocol 정의 default는 TCP
      port: 80 # 노출할 port 지정, target port를 노출하고자 하는 외부 포트
      targetPort: 8080 # container의 target port 지정 (이 app의 경우 수신 대기의 port가 8080이므로)
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer # 사용할 타입 설정, default 값은 ClusterIP
  # type의 종류
  # ClusterIP: 내부적으로 노출된 IP로 클러스터 내부에서만 연결 가능
  # NodePort: 기본적으로 실행되는 worker node의 ip와 port에 노출
  # LoadBalencer:  외부와 연결을 원하는 경우 사용