apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer # 외부에서 접속 가능하도록 셋팅
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: tasks-api
          image: mrk0607/kub-dep-tasks
          # task를 저장할 수 있는 db와 인증을 위한 주소를 환경 변수로 셋팅
          env:
            - name: MONGODB_CONNECTION_URI
              # 예시 db 주소
              value: 'mongodb+srv://hyeon:wk4nFupsbntPbB3l@cluster0.ntrwp.mongodb.net/users?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
